export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INITIALIZE_INGREDIENTS_FAILED = "INITIALIZE_INGREDIENTS_FAILED";