export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INITIALIZE_INGREDIENTS_FAILED = 'INITIALIZE_INGREDIENTS_FAILED';

export const INITIALIZE_CHECKOUT = 'INITIALIZE_CHECKOUT';
export const START_PURCHSASE = 'START_PURCHASE';
export const COMPLETE_PURCHASE_SUCCESS = 'COMPLETE_PURCHASE_SUCCESS';
export const COMPLETE_PURCHASE_FAILED = 'COMPLETE_PURCHASE_FAILED';

export const INITIALIZE_FETCHED_ORDERS = 'INITIALIZE_FETCHED_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const START_AUTHENTICATION = 'START_AUTHENTICATION';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED';